alias: Spara daglig förbrukning max
description: Spara max förbrukning varje dag för Apexchart statistik 
triggers:
  - minutes: "59"
    seconds: "58"
    hours: "23"
    trigger: time_pattern
conditions: []
actions:
  - data:
      value: "{{ states('sensor.arets_elforbrukning_total') }}"
    action: input_number.set_value
    target:
      entity_id: input_number.arets_elforbrukning_nuvarande
mode: single
