#  Meteorologisk årstid v 1.1.1
#
#  Denna yaml-fil beräknar den Meteorologiska årstiden enligt SMHIs definition baserat på temperaturen där du bor.
#  Förbättrad logik för nollställning av räknare och datumhantering.
#
#  Installation kopiera denna fil till din packages mapp och uppdatera sensorn nedan
#

#Definitioner SMHI https://www.smhi.se/vader/observationer/arstidskarta
# Vinter: <= 0.0°C, 5 dygn i följd. Ankomst = dag 1.
# Vår: > 0.0°C, 7 dygn i följd. Ankomst = dag 1. Tidigast ankomst 15 feb, senast ankomst 31 jul.
# Sommar: >= 10.0°C, 5 dygn i följd. Ankomst = dag 1.
# Höst: < 10.0°C, 5 dygn i följd. Ankomst = dag 1. Tidigast ankomst 1 aug, senast ankomst 14 feb.

# OBS! Ersätt sensor.genomsnittlig_utomhus_temp med din egen temperatursensor!
sensor:
  - platform: statistics
    name: "24 Hour Average Temperature"
    entity_id: sensor.genomsnittlig_utomhus_temp  # Ersätt med din temperatursensor 
    unique_id: meteorological_season_24_avg_temp_sensor
    state_characteristic: mean
    max_age:
      hours: 24
    precision: 1

input_datetime:
  mst_spring_arrival_date:
    name: Vårens ankomstdatum
    has_date: true
    has_time: false
  mst_summer_arrival_date:
    name: Sommarens ankomstdatum
    has_date: true
    has_time: false
  mst_autumn_arrival_date:
    name: Höstens ankomstdatum
    has_date: true
    has_time: false
  mst_winter_arrival_date:
    name: Vinterns ankomstdatum
    has_date: true
    has_time: false

input_boolean:
  mst_winter_date_set:
    name: "Vinterns datum satt"
    icon: mdi:snowflake-check
  mst_spring_date_set:
    name: "Vårens datum satt"
    icon: mdi:flower-tulip-outline
  mst_summer_date_set:
    name: "Sommarens datum satt"
    icon: mdi:sun-thermometer-outline
  mst_autumn_date_set:
    name: "Höstens datum satt"
    icon: mdi:leaf-maple

counter:
  mst_spring_days:
    name: Antal vårdygn i följd
    initial: 0
    step: 1
    minimum: 0
    maximum: 7 # Max 7 för vår
  mst_summer_days:
    name: Antal sommardygn i följd
    initial: 0
    step: 1
    minimum: 0
    maximum: 5 # Max 5 för sommar
  mst_autumn_days:
    name: Antal höstdygn i följd
    initial: 0
    step: 1
    minimum: 0
    maximum: 5 # Max 5 för höst
  mst_winter_days:
    name: Antal vinterdygn i följd
    initial: 0
    step: 1
    minimum: 0
    maximum: 5 # Max 5 för vinter

template:
  - trigger:
      - platform: state
        entity_id:
          - input_boolean.mst_winter_date_set
          - input_boolean.mst_spring_date_set
          - input_boolean.mst_summer_date_set
          - input_boolean.mst_autumn_date_set
          - counter.mst_winter_days
          - counter.mst_spring_days
          - counter.mst_summer_days
          - counter.mst_autumn_days
          - automation.meteorologisk_arstid_berakna
    sensor:
      - name: "Meteorologisk årstid"
        unique_id: mst_meteorological_season_sensor
        # State based on which season's date is currently marked as set
        state: >
          {% if is_state('input_boolean.mst_winter_date_set', 'on') %}
            Vinter
          {% elif is_state('input_boolean.mst_spring_date_set', 'on') %}
            Vår
          {% elif is_state('input_boolean.mst_summer_date_set', 'on') %}
            Sommar
          {% elif is_state('input_boolean.mst_autumn_date_set', 'on') %}
            Höst
          {% else %}
            Ej Beräknad
          {% endif %}
        attributes:
          Ankomstdatum: >
            {% if is_state('input_boolean.mst_winter_date_set', 'on') %}
              {{ states('input_datetime.mst_winter_arrival_date') }}
            {% elif is_state('input_boolean.mst_spring_date_set', 'on') %}
              {{ states('input_datetime.mst_spring_arrival_date') }}
            {% elif is_state('input_boolean.mst_summer_date_set', 'on') %}
              {{ states('input_datetime.mst_summer_arrival_date') }}
            {% elif is_state('input_boolean.mst_autumn_date_set', 'on') %}
              {{ states('input_datetime.mst_autumn_arrival_date') }}
            {% else %}
              Ej registrerat
            {% endif %}
          Förra dygnets medeltemp: "{{ states('sensor.24_hour_average_temperature') | float(0) }}"
          Senast uppdaterad: "{{ now().strftime('%Y-%m-%d %H:%M') }}"
          # Showing counters for debugging/interest
          Vinterdygn: "{{ states('counter.mst_winter_days') }}/5"
          Vårdygn: "{{ states('counter.mst_spring_days') }}/7"
          Sommardygn: "{{ states('counter.mst_summer_days') }}/5"
          Höstdygn: "{{ states('counter.mst_autumn_days') }}/5"
          # Historical arrival dates ( Newer than 2 years)
          Vårens ankomstdatum: "{{ states('input_datetime.mst_spring_arrival_date') if (states('input_datetime.mst_spring_arrival_date') | as_timestamp) > (now() - timedelta(days=730)).timestamp()  else '' }}"
          Sommarens ankomstdatum: "{{ states('input_datetime.mst_summer_arrival_date') if (states('input_datetime.mst_summer_arrival_date') | as_timestamp) > (now() - timedelta(days=730)).timestamp()  else '' }}"
          Höstens ankomstdatum: "{{ states('input_datetime.mst_autumn_arrival_date') if (states('input_datetime.mst_autumn_arrival_date') | as_timestamp) > (now() - timedelta(days=730)).timestamp() else '' }}"
          Vinterns ankomstdatum: "{{ states('input_datetime.mst_winter_arrival_date') if (states('input_datetime.mst_winter_arrival_date') | as_timestamp) > (now() - timedelta(days=730)).timestamp()  else '' }}"

        icon: >
          {% if is_state('input_boolean.mst_winter_date_set', 'on') %}
            mdi:snowflake
          {% elif is_state('input_boolean.mst_spring_date_set', 'on') %}
            mdi:flower
          {% elif is_state('input_boolean.mst_summer_date_set', 'on') %}
            mdi:sunglasses
          {% elif is_state('input_boolean.mst_autumn_date_set', 'on') %}
            mdi:leaf
          {% else %}
            mdi:progress-question # Icon indicating undetermined state
          {% endif %}

automation:
  - alias: "Meteorologisk årstid Beräkna"
    id: calculate_meteorological_seasons_automation
    trigger:
      - platform: time
        at: "00:01:00"
    action:
      - variables:
          average_temp: "{{ states('sensor.24_hour_average_temperature') | float(none) }}"
          temp_available: "{{ average_temp is not none }}"

      # === Steg 1: Validera Temperatur ===
      - if: "{{ not temp_available }}"
        then:
          - service: logbook.log
            data:
              name: Meteorologisk årstid
              message: "Temperaturdata saknas. Kan inte beräkna årstid."
              domain: automation
          - service: system_log.write
            data:
              level: warning
              message: "Meteorologisk årstid: Temperaturdata är otillgänglig, beräkning avbruten."
          - stop: "Temperaturdata otillgänglig"

      # === Steg 2: Definiera Dagens Villkor ===
      - variables:
          # Temperaturvillkor
          is_winter_temp: "{{ average_temp <= 0.0 }}"
          is_summer_temp: "{{ average_temp >= 10.0 }}"
          is_spring_potential_temp: "{{ average_temp > 0.0 }}"
          is_autumn_potential_temp: "{{ average_temp < 10.0 }}"

          # Datumvillkor (när en årstid kan börja räknas)
          today_is_spring_period: >-
            {% set m = now().month %}
            {% set d = now().day %}
            {{ (m == 2 and d >= 15) or (m > 2 and m <= 7) }}
          today_is_autumn_period: >-
            {% set m = now().month %}
            {% set d = now().day %}
            {{ (m >= 8) or (m == 1) or (m == 2 and d <= 14) }}
            
          # NYTT: Kontrollera vilken årstid som är aktiv just nu
          current_season_is_winter: "{{ is_state('input_boolean.mst_winter_date_set', 'on') }}"
          current_season_is_spring: "{{ is_state('input_boolean.mst_spring_date_set', 'on') }}"
          current_season_is_summer: "{{ is_state('input_boolean.mst_summer_date_set', 'on') }}"
          current_season_is_autumn: "{{ is_state('input_boolean.mst_autumn_date_set', 'on') }}"
          no_season_is_set: "{{ not (current_season_is_winter or current_season_is_spring or current_season_is_summer or current_season_is_autumn) }}"

      # === Steg 3: Uppdatera Räknare (med korrekt ordningsföljd) ===
      # Vinterräknare: kan bara räknas om det är höst nu (eller om ingen årstid är satt)
      - if: "{{ is_winter_temp and (current_season_is_autumn or no_season_is_set) }}"
        then:
          - service: counter.increment
            target: { entity_id: counter.mst_winter_days }
        else:
          - service: counter.reset
            target: { entity_id: counter.mst_winter_days }

      # Vårräknare: kan bara räknas om det är vinter nu (eller om ingen årstid är satt) och inom rätt period
      - if: "{{ is_spring_potential_temp and today_is_spring_period and (current_season_is_winter or no_season_is_set) }}"
        then:
          - service: counter.increment
            target: { entity_id: counter.mst_spring_days }
        else:
          - service: counter.reset
            target: { entity_id: counter.mst_spring_days }

      # Sommarräknare: kan bara räknas om det är vår nu (eller om ingen årstid är satt)
      - if: "{{ is_summer_temp and (current_season_is_spring or no_season_is_set) }}"
        then:
          - service: counter.increment
            target: { entity_id: counter.mst_summer_days }
        else:
          - service: counter.reset
            target: { entity_id: counter.mst_summer_days }

      # Hösträknare: kan bara räknas om det är sommar nu (eller om ingen årstid är satt) och inom rätt period
      - if: "{{ is_autumn_potential_temp and today_is_autumn_period and (current_season_is_summer or no_season_is_set) }}"
        then:
          - service: counter.increment
            target: { entity_id: counter.mst_autumn_days }
        else:
          - service: counter.reset
            target: { entity_id: counter.mst_autumn_days }

      # === Steg 4: Kontrollera om en ny årstid har anlänt ===
      - variables:
          winter_c: "{{ states('counter.mst_winter_days') | int(0) }}"
          spring_c: "{{ states('counter.mst_spring_days') | int(0) }}"
          summer_c: "{{ states('counter.mst_summer_days') | int(0) }}"
          autumn_c: "{{ states('counter.mst_autumn_days') | int(0) }}"

      - choose:
          # --- Vinter anländer? Kan bara ske från Höst ---
          - conditions: "{{ winter_c >= 5 and (current_season_is_autumn or no_season_is_set) }}"
            sequence:
              - service: input_datetime.set_datetime
                target: { entity_id: input_datetime.mst_winter_arrival_date }
                data: { date: "{{ (now() - timedelta(days=5)).strftime('%Y-%m-%d') }}" }
              - service: input_boolean.turn_on
                target: { entity_id: input_boolean.mst_winter_date_set }
              - service: input_boolean.turn_off
                target:
                  entity_id:
                    - input_boolean.mst_spring_date_set
                    - input_boolean.mst_summer_date_set
                    - input_boolean.mst_autumn_date_set
                        
          # --- Höst anländer? Kan bara ske från Sommar ---
          - conditions: "{{ autumn_c >= 5 and (current_season_is_summer or no_season_is_set) }}"
            sequence:
              - variables:
                  autumn_arrival_dt_obj: "{{ (now() - timedelta(days=5)) }}"
                  latest_autumn_ok: >-
                    {% set arr_m = (autumn_arrival_dt_obj | as_datetime).month %}
                    {% set arr_d = (autumn_arrival_dt_obj | as_datetime).day %}
                    {{ (arr_m >= 8) or (arr_m == 1) or (arr_m == 2 and arr_d <= 14) }}
              - if: "{{ latest_autumn_ok }}"
                then:
                  - service: input_datetime.set_datetime
                    target: { entity_id: input_datetime.mst_autumn_arrival_date }
                    data: { date: "{{ autumn_arrival_dt_obj.strftime('%Y-%m-%d') }}" }
                  - service: input_boolean.turn_on
                    target: { entity_id: input_boolean.mst_autumn_date_set }
                  - service: input_boolean.turn_off
                    target:
                      entity_id:
                        - input_boolean.mst_winter_date_set
                        - input_boolean.mst_spring_date_set
                        - input_boolean.mst_summer_date_set        
                        
          # --- Sommar anländer? Kan bara ske från Vår ---
          - conditions: "{{ summer_c >= 5 and (current_season_is_spring or no_season_is_set) }}"
            sequence:
              - service: input_datetime.set_datetime
                target: { entity_id: input_datetime.mst_summer_arrival_date }
                data: { date: "{{ (now() - timedelta(days=5)).strftime('%Y-%m-%d') }}" }
              - service: input_boolean.turn_on
                target: { entity_id: input_boolean.mst_summer_date_set }
              - service: input_boolean.turn_off
                target:
                  entity_id:
                    - input_boolean.mst_winter_date_set
                    - input_boolean.mst_spring_date_set
                    - input_boolean.mst_autumn_date_set
                        
          # --- Vår anländer? Kan bara ske från Vinter och Höst ---
          - conditions: "{{ spring_c >= 7 and (current_season_is_winter or current_season_is_spring or no_season_is_set) }}"
            sequence
              - variables:
                  spring_arrival_dt_obj: "{{ (now() - timedelta(days=7)) }}"
                  latest_spring_ok: "{{ ((spring_arrival_dt_obj | as_datetime).month * 100 + (spring_arrival_dt_obj | as_datetime).day) <= 731 }}"
              - if: "{{ latest_spring_ok }}"
                then:
                  - service: input_datetime.set_datetime
                    target: { entity_id: input_datetime.mst_spring_arrival_date }
                    data: { date: "{{ spring_arrival_dt_obj.strftime('%Y-%m-%d') }}" }
                  - service: input_boolean.turn_on
                    target: { entity_id: input_boolean.mst_spring_date_set }
                  - service: input_boolean.turn_off
                    target:
                      entity_id:
                        - input_boolean.mst_winter_date_set
                        - input_boolean.mst_summer_date_set
                        - input_boolean.mst_autumn_date_set
    mode: single

