blueprint:
  name: Shelly Dimmer 2 Virtual Controller (Gen1 - wait_for_trigger fixed)
  description: >
    Shelly Dimmer 2 (Gen1) virtual controller for lights.
    - Single click → Toggle (unless a second single occurs within window)
    - Double click (two singles within window) → Max brightness
    - Hold → Continuous dim (direction alternates)
  domain: automation
  author: HomeAssistant Helper (GPT-5)
  homeassistant:
    min_version: 2025.10.0

  input:
    shelly_device:
      name: Shelly Device
      selector:
        device:
          integration: shelly

    channel:
      name: Channel
      default: 1
      selector:
        number:
          min: 1
          max: 2
          mode: box

    hold_sensor:
      name: (Optional) Hold Sensor
      description: Binary sensor ON while button pressed (optional stop condition)
      default: []
      selector:
        entity:
          domain: binary_sensor

    target_light:
      name: Target Light(s)
      selector:
        target:
          entity:
            domain: light

    dim_direction_helper:
      name: Dim Direction Helper
      description: input_boolean helper to toggle dim direction up/down
      selector:
        entity:
          domain: input_boolean

    dim_step:
      name: Dimming Step (%)
      default: 5
      selector:
        number:
          min: 1
          max: 20
          step: 1
          mode: slider
          unit_of_measurement: "%"

    dim_delay:
      name: Dimming Delay (seconds)
      default: 0.2
      selector:
        number:
          min: 0.05
          max: 1.0
          step: 0.05
          mode: slider
          unit_of_measurement: "s"

    double_click_window:
      name: Double Click Window (seconds)
      default: 0.8
      selector:
        number:
          min: 0.2
          max: 1.5
          step: 0.1
          mode: slider
          unit_of_measurement: "s"

mode: restart
max_exceeded: silent

variables:
  device_id: !input shelly_device
  channel: !input channel
  light_target: !input target_light
  dim_toggle: !input dim_direction_helper
  hold_sensor: !input hold_sensor
  dim_step: !input dim_step
  dim_delay: !input dim_delay
  double_click_window: !input double_click_window

trigger:
  - platform: event
    event_type: shelly.click
    id: single
    event_data:
      device_id: !input shelly_device
      click_type: single
      channel: !input channel

  - platform: event
    event_type: shelly.click
    id: long
    event_data:
      device_id: !input shelly_device
      click_type: long
      channel: !input channel

  - platform: event
    event_type: shelly.click
    id: single_long
    event_data:
      device_id: !input shelly_device
      click_type: single_long
      channel: !input channel

  - platform: event
    event_type: shelly.click
    id: long_single
    event_data:
      device_id: !input shelly_device
      click_type: long_single
      channel: !input channel

action:
  - choose:
      # --- Hold (long variants) → Continuous dimming loop ---
      - conditions:
          - condition: trigger
            id: long
        sequence:
          - service: input_boolean.toggle
            target:
              entity_id: "{{ dim_toggle }}"
          - variables:
              dim_up: "{{ is_state(dim_toggle, 'on') }}"
          - repeat:
              while:
                - condition: template
                  value_template: >
                    {% if hold_sensor != [] %}
                      {{ is_state(hold_sensor, 'on') }}
                    {% else %}
                      true
                    {% endif %}
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: "{{ dim_step if dim_up else -dim_step }}"
                - delay:
                    seconds: "{{ dim_delay }}"

      # --- Single click: wait for potential double click (with validation) ---
      - conditions:
          - condition: trigger
            id: single
        sequence:
          # Wait for a second single click within window
          - wait_for_trigger:
              - platform: event
                event_type: shelly.click
                event_data:
                  device_id: !input shelly_device
                  click_type: single
                  channel: !input channel
            timeout:
              seconds: "{{ double_click_window }}"
            continue_on_timeout: true

          # Decide: is it a valid double click?
          - choose:
              - conditions:
                  # wait.trigger did not timeout AND waited event is a different event instance
                  - condition: template
                    value_template: >
                      {{ (not wait.trigger.timeout)
                         and (wait.trigger.event is defined)
                         and (trigger.event.context is defined)
                         and (wait.trigger.event.context.id != trigger.event.context.id)
                         and (as_timestamp(wait.trigger.event.time_fired) > as_timestamp(trigger.event.time_fired)) }}
                sequence:
                  # Valid double click: go to full brightness
                  - service: light.turn_on
                    target: !input target_light
                    data:
                      brightness_pct: 100

              - conditions:
                  # Otherwise: treat as single click
                  - condition: template
                    value_template: >
                      {{ wait.trigger.timeout or wait.trigger.event is not defined
                         or (wait.trigger.event.context.id == trigger.event.context.id)
                         or (as_timestamp(wait.trigger.event.time_fired) <= as_timestamp(trigger.event.time_fired)) }}
                sequence:
                  - service: light.toggle
                    target: !input target_light
