blueprint:
  name: Shelly Virtual Dimmer Controller (Final)
  description: >
    Use a Shelly Dimmer 2 input as a virtual dimmer for any light(s).
    Single = toggle, Double = max brightness, Long = continuous dim (alternates up/down).
  domain: automation
  author: HomeAssistant Helper (GPT-5)
  homeassistant:
    min_version: 2025.10.0

  input:
    shelly_device:
      name: Shelly Dimmer 2 Device
      description: Select the Shelly device.
      selector:
        device:
          integration: shelly
    button_input:
      name: Button Input
      description: Usually "button" or "button1" for Shelly Dimmer 2.
      default: button
      selector:
        select:
          options:
            - button
            - button1
            - button2
    hold_sensor:
      name: (Optional) Hold Sensor
      description: Binary sensor ON while button pressed (used to stop dimming).
      default: []
      selector:
        entity:
          domain: binary_sensor
    target_light:
      name: Target Light(s)
      selector:
        target:
          entity:
            domain: light
    dim_direction_helper:
      name: Dim Direction Helper
      description: input_boolean used to toggle dim direction.
      selector:
        entity:
          domain: input_boolean

mode: restart
max_exceeded: silent

variables:
  light_target: !input target_light
  dim_toggle: !input dim_direction_helper
  hold_sensor: !input hold_sensor
  button_input: !input button_input

trigger:
  # ✅ This syntax matches the schema from your error messages.
  - platform: device
    device_id: !input shelly_device
    domain: shelly
    type: single
    subtype: !input button_input
    id: single
  - platform: device
    device_id: !input shelly_device
    domain: shelly
    type: double
    subtype: !input button_input
    id: double
  - platform: device
    device_id: !input shelly_device
    domain: shelly
    type: triple
    subtype: !input button_input
    id: triple
  - platform: device
    device_id: !input shelly_device
    domain: shelly
    type: long
    subtype: !input button_input
    id: long
  - platform: device
    device_id: !input shelly_device
    domain: shelly
    type: single_long
    subtype: !input button_input
    id: single_long
  - platform: device
    device_id: !input shelly_device
    domain: shelly
    type: long_single
    subtype: !input button_input
    id: long_single

action:
  - choose:
      # --- Single Click → Toggle light ---
      - conditions:
          - condition: trigger
            id: single
        sequence:
          - service: light.toggle
            target: !input target_light

      # --- Double Click → Max brightness ---
      - conditions:
          - condition: trigger
            id: double
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_pct: 100

      # --- Triple Click → Turn off ---
      - conditions:
          - condition: trigger
            id: triple
        sequence:
          - service: light.turn_off
            target: !input target_light

      # --- Long / Single_Long / Long_Single → Continuous dim ---
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['long', 'single_long', 'long_single'] }}"
        sequence:
          - service: input_boolean.toggle
            target:
              entity_id: "{{ dim_toggle }}"
          - variables:
              dim_up: "{{ is_state(dim_toggle, 'on') }}"
          - repeat:
              while:
                - condition: template
                  value_template: >
                    {% if hold_sensor != [] %}
                      {{ is_state(hold_sensor, 'on') }}
                    {% else %}
                      true
                    {% endif %}
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: "{{ 5 if dim_up else -5 }}"
                - delay: "00:00:0.2"

