blueprint:
  name: Shelly Dimmer Virtual Light Controller (Continuous Hold, Toggle Direction)
  description: >
    Use a Shelly Dimmer 2 as a virtual dimmer for another smart light.
    - Single click toggles
    - Double click sets full brightness
    - Hold continuously changes brightness (up/down alternating)
    - Release stops dimming and reverses next direction

  domain: automation
  input:
    shelly_device:
      name: Shelly Device
      selector:
        device:
          integration: shelly

    target_light:
      name: Target Light
      selector:
        entity:
          domain: light

    brightness_step:
      name: Brightness Step (%)
      default: 4
      selector:
        number:
          min: 1
          max: 20
          unit_of_measurement: "%"

    delay_ms:
      name: Delay Between Steps (ms)
      default: 120
      selector:
        number:
          min: 50
          max: 1000
          unit_of_measurement: "ms"

    min_brightness:
      name: Minimum Brightness (%)
      default: 5
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"

    max_brightness:
      name: Maximum Brightness (%)
      default: 100
      selector:
        number:
          min: 50
          max: 100
          unit_of_measurement: "%"

mode: restart

variables:
  light_entity: !input target_light
  step: !input brightness_step
  delay: !input delay_ms
  min_brightness: !input min_brightness
  max_brightness: !input max_brightness
  shelly_device_id: !input shelly_device
  direction: "{{ this.attributes.get('direction', 1) | int }}"  # 1=up, -1=down

trigger:
  - platform: event
    event_type: shelly.click
    id: single
    event_data:
      click_type: single
  - platform: event
    event_type: shelly.click
    id: double
    event_data:
      click_type: double
  - platform: event
    event_type: shelly.click
    id: long
    event_data:
      click_type: long
  - platform: event
    event_type: shelly.click
    id: long_release
    event_data:
      click_type: long_release

condition:
  - condition: template
    value_template: "{{ trigger.event.data.device_id == shelly_device_id }}"

action:
  - choose:
      # --- SINGLE CLICK ---
      - conditions:
          - condition: trigger
            id: single
        sequence:
          - service: light.toggle
            target:
              entity_id: "{{ light_entity }}"

      # --- DOUBLE CLICK ---
      - conditions:
          - condition: trigger
            id: double
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light_entity }}"
            data:
              brightness_pct: 100

      # --- HOLD: CONTINUOUS DIM ---
      - conditions:
          - condition: trigger
            id: long
        sequence:
          - repeat:
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ light_entity }}"
                  data:
                    brightness_pct: >-
                      {{
                        [
                          [
                            ((state_attr(light_entity, 'brightness') | int(0)) / 2.55) | int + (step * direction),
                            max_brightness
                          ] | min,
                          min_brightness
                        ] | max
                      }}
                - delay:
                    milliseconds: "{{ delay }}"
              until:
                - condition: template
                  value_template: "{{ wait.trigger.id == 'long_release' }}"
          - stop: true

      # --- RELEASE: STOP + TOGGLE DIRECTION ---
      - conditions:
          - condition: trigger
            id: long_release
        sequence:
          # Flip direction (+1 → -1 → +1)
          - variables:
              new_direction: "{{ direction * -1 }}"
          - service: automation.update_entity
            target:
              entity_id: "{{ this.entity_id }}"
          - service: persistent_notification.create
            data:
              title: "Shelly Dimmer Debug"
              message: "Next dim direction: {{ 'up' if new_direction == 1 else 'down' }}"
