blueprint:
  name: Shelly Dimmer 2 Virtual Controller (Gen1 - reliable double click)
  description: >
    Virtual controller for controlling other lights via Shelly Dimmer 2.
    - Single click: Toggle lights
    - Double click: Max brightness (two single clicks within window)
    - Hold (long): Continuous dimming (direction toggles each hold)
  domain: automation
  author: HomeAssistant Helper (GPT-5)
  homeassistant:
    min_version: 2025.10.0

  input:
    shelly_device:
      name: Shelly Device
      selector:
        device:
          integration: shelly

    channel:
      name: Channel
      default: 1
      selector:
        number:
          min: 1
          max: 2
          mode: box

    target_light:
      name: Target Light(s)
      selector:
        target:
          entity:
            domain: light

    hold_sensor:
      name: (Optional) Hold Sensor
      description: Binary sensor that is ON while button is pressed.
      default: []
      selector:
        entity:
          domain: binary_sensor

    dim_direction_helper:
      name: Dim Direction Helper
      description: input_boolean helper toggling dim direction up/down
      selector:
        entity:
          domain: input_boolean

    dim_step:
      name: Dimming Step (%)
      default: 5
      selector:
        number:
          min: 1
          max: 20
          step: 1
          mode: slider
          unit_of_measurement: "%"

    dim_delay:
      name: Dimming Delay (seconds)
      default: 0.2
      selector:
        number:
          min: 0.05
          max: 1.0
          step: 0.05
          mode: slider
          unit_of_measurement: "s"

    double_click_window:
      name: Double Click Window (seconds)
      default: 0.8
      selector:
        number:
          min: 0.2
          max: 1.5
          step: 0.1
          mode: slider
          unit_of_measurement: "s"

mode: restart
max_exceeded: silent

variables:
  device_id: !input shelly_device
  channel: !input channel
  light_target: !input target_light
  dim_toggle: !input dim_direction_helper
  hold_sensor: !input hold_sensor
  dim_step: !input dim_step
  dim_delay: !input dim_delay
  double_click_window: !input double_click_window

trigger:
  - platform: event
    event_type: shelly.click
    id: single
    event_data:
      device_id: !input shelly_device
      click_type: single
      channel: !input channel

  - platform: event
    event_type: shelly.click
    id: long
    event_data:
      device_id: !input shelly_device
      click_type: long
      channel: !input channel

action:
  - choose:
      # --- HOLD (long) triggers dimming loop ---
      - conditions:
          - condition: trigger
            id: long
        sequence:
          - service: input_boolean.toggle
            target:
              entity_id: "{{ dim_toggle }}"
          - variables:
              dim_up: "{{ is_state(dim_toggle, 'on') }}"
          - repeat:
              while:
                - condition: template
                  value_template: >
                    {% if hold_sensor != [] %}
                      {{ is_state(hold_sensor, 'on') }}
                    {% else %}
                      true
                    {% endif %}
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: "{{ dim_step if dim_up else -dim_step }}"
                - delay:
                    seconds: "{{ dim_delay }}"

      # --- SINGLE click with double-click detection (timeout method) ---
      - conditions:
          - condition: trigger
            id: single
        sequence:
          # Wait for second click (single) within timeout
          - wait_for_trigger:
              - platform: event
                event_type: shelly.click
                event_data:
                  device_id: !input shelly_device
                  click_type: single
                  channel: !input channel
            timeout:
              seconds: "{{ double_click_window }}"
            continue_on_timeout: true

          - if:
              # Single click = no second click detected
              - condition: template
                value_template: "{{ wait.trigger == none }}"
            then:
              - service: light.toggle
                target: !input target_light
            else:
              - service: light.turn_on
                target: !input target_light
                data:
                  brightness_pct: 100
