blueprint:
  name: Shelly Dimmer - Virtual Click Controller
  description: >-
    Handles single, double, and other click events from a Shelly Dimmer 2.
    - Single Click: Toggles light
    - Double Click: Sets light to 100%
    - All Clicks (single, double, triple, etc.): Toggle the dim direction helper.
    
    This blueprint is part 1 of 2. It is designed to work with the
    "Virtual Hold-to-Dim" blueprint.

  domain: automation
  input:
    shelly_device:
      name: Shelly Dimmer 2 Device
      description: The Shelly Dimmer 2 device that sends shelly.click events.
      selector:
        device:
          integration: shelly
          model: Shelly Dimmer 2 (SHDM-2)
    
    target_light:
      name: Target Light
      description: The light entity or group to control.
      selector:
        entity:
          domain: light

    dim_direction_helper:
      name: Dim Direction Helper
      description: An (input_boolean) helper to store the dimming direction (on=UP, off=DOWN).
      selector:
        entity:
          domain: input_boolean

mode: single

# Capture the click_type from the trigger
variables:
  click_type: "{{ trigger.event.data.click_type }}"

# Trigger on any shelly.click event from the selected device
trigger:
  - platform: event
    event_type: shelly.click
    event_data:
      device_id: !input shelly_device

action:
  # First, toggle the dim direction on *every* click type, as requested.
  - service: input_boolean.toggle
    target:
      entity_id: !input dim_direction_helper

  # Next, perform the action based on the click type
  - choose:
      # --- SINGLE CLICK: Toggle Light ---
      - conditions:
          - "{{ click_type == 'single' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input target_light

      # --- DOUBLE CLICK: Max Brightness ---
      - conditions:
          - "{{ click_type == 'double' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness_pct: 100
      
      # --- OTHER CLICKS (triple, long, single_long, long_single) ---
      # No light action, but the dim direction was already toggled above.
      - conditions:
          - "{{ click_type in ['triple', 'long', 'single_long', 'long_single'] }}"
        sequence: [] # Do nothing else
