blueprint:
  name: Shelly Dimmer 2 Virtual Light Controller (Continuous Hold)
  description: >
    Use a Shelly Dimmer 2 switch to control another light via events.
    - Single click: toggle
    - Double click: full brightness
    - Hold: continuous dimming
    - Release: stop dimming and reverse direction next time
  domain: automation
  author: HomeAssistant Helper GPT-5
  input:
    shelly_device:
      name: Shelly Device
      description: Select your Shelly Dimmer 2 device
      selector:
        device:
          integration: shelly

    target_light:
      name: Target Light
      description: The light to control
      selector:
        entity:
          domain: light

    brightness_step:
      name: Brightness Step (%)
      default: 4
      selector:
        number:
          min: 1
          max: 20
          unit_of_measurement: "%"

    delay_ms:
      name: Delay Between Steps (ms)
      default: 120
      selector:
        number:
          min: 50
          max: 1000
          unit_of_measurement: "ms"

mode: restart

variables:
  light_entity: !input target_light
  shelly_device_id: !input shelly_device
  step: !input brightness_step
  delay: !input delay_ms
  # Store direction (persisted via attributes)
  direction: "{{ this.attributes.get('direction', 1) | int }}"  # 1 = up, -1 = down

trigger:
  - platform: event
    event_type: shelly.click
    id: single
    event_data:
      click_type: single
  - platform: event
    event_type: shelly.click
    id: double
    event_data:
      click_type: double
  - platform: event
    event_type: shelly.click
    id: long
    event_data:
      click_type: long
  - platform: event
    event_type: shelly.click
    id: long_release
    event_data:
      click_type: long_release

condition:
  - condition: template
    value_template: "{{ trigger.event.data.device_id == shelly_device_id }}"

action:
  - choose:
      # ───── SINGLE CLICK ─────
      - conditions:
          - condition: trigger
            id: single
        sequence:
          - service: light.toggle
            target:
              entity_id: "{{ light_entity }}"

      # ───── DOUBLE CLICK ─────
      - conditions:
          - condition: trigger
            id: double
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light_entity }}"
            data:
              brightness_pct: 100

      # ───── LONG PRESS: start dimming ─────
      - conditions:
          - condition: trigger
            id: long
        sequence:
          - service: script.turn_on
            target:
              entity_id: script.shelly_dimmer_hold
            data:
              variables:
                light_entity: "{{ light_entity }}"
                step: "{{ step }}"
                delay: "{{ delay }}"
                direction: "{{ direction }}"

      # ───── RELEASE: stop + flip direction ─────
      - conditions:
          - condition: trigger
            id: long_release
        sequence:
          - service: script.turn_off
            target:
              entity_id: script.shelly_dimmer_hold
          # flip dim direction
          - variables:
              new_direction: "{{ direction * -1 }}"
          - service: automation.update_entity
            target:
              entity_id: "{{ this.entity_id }}"
          - service: logbook.log
            data:
              name: "Shelly Dimmer"
              message: "Next dim direction: {{ 'up' if new_direction == 1 else 'down' }}"
