blueprint:
  name: Shelly Dimmer 2 Virtual Controller (Gen1 – Binary Sensor Timing)
  description: >
    Control other lights with a Shelly Dimmer 2 button.
    - Single click → toggle
    - Double click → max brightness
    - Hold → continuous dimming (direction toggles each time)
  domain: automation
  author: HomeAssistant Helper (GPT-5)

  input:
    button_sensor:
      name: Button Binary Sensor
      description: Binary sensor that is ON while the button is pressed.
      selector:
        entity:
          domain: binary_sensor

    target_light:
      name: Target Light(s)
      selector:
        target:
          entity:
            domain: light

    dim_direction_helper:
      name: Dim Direction Helper
      description: input_boolean helper toggled each hold (up/down)
      selector:
        entity:
          domain: input_boolean

    dim_step:
      name: Dimming Step (%)
      default: 5
      selector:
        number:
          min: 1
          max: 20
          step: 1
          unit_of_measurement: "%"

    dim_delay:
      name: Dimming Delay (s)
      default: 0.2
      selector:
        number:
          min: 0.05
          max: 1.0
          step: 0.05
          unit_of_measurement: "s"

    double_click_window:
      name: Double Click Window (s)
      default: 0.8
      selector:
        number:
          min: 0.2
          max: 1.5
          step: 0.1
          unit_of_measurement: "s"

mode: restart
max_exceeded: silent

variables:
  light_target: !input target_light
  dim_toggle: !input dim_direction_helper
  dim_step: !input dim_step
  dim_delay: !input dim_delay
  double_click_window: !input double_click_window

trigger:
  # Fires when the button is pressed (binary_sensor goes ON)
  - platform: state
    entity_id: !input button_sensor
    from: "off"
    to: "on"
    id: press

  # Fires when held (stays ON for > 0.5 s)
  - platform: state
    entity_id: !input button_sensor
    to: "on"
    for:
      seconds: 0.5
    id: hold

action:
  - choose:
      # --- HOLD (continuous dim) ---
      - conditions:
          - condition: trigger
            id: hold
        sequence:
          - service: input_boolean.toggle
            target:
              entity_id: "{{ dim_toggle }}"
          - variables:
              dim_up: "{{ is_state(dim_toggle, 'on') }}"
          - repeat:
              while:
                - condition: state
                  entity_id: !input button_sensor
                  state: "on"
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: "{{ dim_step if dim_up else -dim_step }}"
                - delay:
                    seconds: "{{ dim_delay }}"

      # --- CLICK / DOUBLE-CLICK detection ---
      - conditions:
          - condition: trigger
            id: press
        sequence:
          - variables:
              last_press: "{{ this.attributes.last_press | default(0) }}"
              now_ts: "{{ as_timestamp(now()) }}"
              delta: "{{ now_ts - last_press }}"
          - if:
              # Double-click = pressed again quickly
              - condition: template
                value_template: "{{ delta < double_click_window }}"
            then:
              - service: light.turn_on
                target: !input target_light
                data:
                  brightness_pct: 100
            else:
              - service: light.toggle
                target: !input target_light
          # Remember this press time
          - service: automation.trigger
            target:
              entity_id: "{{ this.entity_id }}"
            data:
              variables:
                last_press: "{{ now_ts }}"
