blueprint:
  name: Shelly Dimmer 2 — On/Off + Continuous Dim (no double-click)
  description: >
    Use a Shelly Dimmer 2 button to toggle lights (single click) and
    to continuously dim while holding (long). Double-click logic removed.
  domain: automation
  author: HomeAssistant Helper (GPT-5)
  homeassistant:
    min_version: 2025.10.0

  input:
    shelly_device:
      name: Shelly Device (for event filtering)
      description: Shelly device used to ensure we only react to your device's clicks.
      selector:
        device:
          integration: shelly

    channel:
      name: Channel
      description: Shelly channel (usually 1)
      default: 1
      selector:
        number:
          min: 1
          max: 2
          mode: box

    button_hold_sensor:
      name: (Optional) Hold Binary Sensor
      description: Binary sensor that is ON while the button is physically pressed (recommended).
      default: []
      selector:
        entity:
          domain: binary_sensor

    target_light:
      name: Target Light(s)
      selector:
        target:
          entity:
            domain: light

    dim_direction_helper:
      name: Dim Direction Helper
      description: input_boolean used to toggle dim direction each hold
      selector:
        entity:
          domain: input_boolean

    dim_step:
      name: Dimming Step (%)
      description: Percent change per loop iteration
      default: 5
      selector:
        number:
          min: 1
          max: 20
          step: 1
          mode: slider
          unit_of_measurement: "%"

    dim_delay:
      name: Dimming Delay (s)
      description: Delay between each dim step
      default: 0.2
      selector:
        number:
          min: 0.05
          max: 1.0
          step: 0.05
          mode: slider
          unit_of_measurement: "s"

    max_hold:
      name: Max hold duration (s) when no hold sensor
      description: Safety timeout to stop dim loop if no hold sensor is provided
      default: 30
      selector:
        number:
          min: 1
          max: 600
          step: 1
          unit_of_measurement: "s"

mode: restart
max_exceeded: silent

variables:
  device_id: !input shelly_device
  channel: !input channel
  light_target: !input target_light
  dim_toggle: !input dim_direction_helper
  hold_sensor: !input button_hold_sensor
  dim_step: !input dim_step
  dim_delay: !input dim_delay
  max_hold: !input max_hold

trigger:
  # Single click (toggle)
  - platform: event
    event_type: shelly.click
    id: single
    event_data:
      device_id: !input shelly_device
      click_type: single
      channel: !input channel

  # Long press (start continuous dim)
  - platform: event
    event_type: shelly.click
    id: long
    event_data:
      device_id: !input shelly_device
      click_type: long
      channel: !input channel

action:
  - choose:
      # LONG press -> continuous dim loop
      - conditions:
          - condition: trigger
            id: long
        sequence:
          # Toggle stored dim direction each time a long press begins
          - service: input_boolean.toggle
            target:
              entity_id: "{{ dim_toggle }}"
          - variables:
              dim_up: "{{ is_state(dim_toggle, 'on') }}"
              start_ts: "{{ as_timestamp(now()) }}"
          - repeat:
              while:
                - condition: template
                  value_template: >
                    {# If a hold sensor is provided, loop while it's 'on'. Otherwise loop while elapsed < max_hold #}
                    {% if hold_sensor != [] %}
                      {{ is_state(hold_sensor, 'on') }}
                    {% else %}
                      {{ (as_timestamp(now()) - start_ts) < max_hold }}
                    {% endif %}
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: "{{ dim_step if dim_up else -dim_step }}"
                - delay:
                    seconds: "{{ dim_delay }}"

      # SINGLE click -> Toggle light
      - conditions:
          - condition: trigger
            id: single
        sequence:
          - service: light.toggle
            target: !input target_light
