blueprint:
  name: Shelly Virtual Dimmer Controller (Shelly Dimmer 2)
  description: >
    Use a Shelly Dimmer 2 input as a virtual dimmer controller for other lights.
    Supports single, double, triple, long, single_long, and long_single.
    Single = toggle, Double = max brightness, Long = continuous dim (alternates up/down).
  domain: automation
  author: HomeAssistant Helper (GPT-5)
  homeassistant:
    min_version: 2025.10.0

  input:
    shelly_device:
      name: Shelly Dimmer 2 Device
      description: Select the Shelly device (the input side, not the relay).
      selector:
        device:
          integration: shelly
    input_channel:
      name: Input Channel
      description: Input channel to monitor (usually input0 for Dimmer 2)
      default: input0
      selector:
        select:
          options:
            - input0
            - input1
    hold_sensor:
      name: (Optional) Hold Sensor
      description: Binary sensor that is ON while button pressed (optional, used to stop dimming)
      default: []
      selector:
        entity:
          domain: binary_sensor
    target_light:
      name: Target Light(s)
      selector:
        target:
          entity:
            domain: light
    dim_direction_helper:
      name: Dim Direction Helper
      description: input_boolean used to store dimming direction (up/down)
      selector:
        entity:
          domain: input_boolean

mode: restart
max_exceeded: silent

variables:
  light_target: !input target_light
  dim_toggle: !input dim_direction_helper
  hold_sensor: !input hold_sensor
  input_channel: !input input_channel

trigger:
  # All supported Shelly input click types
  - platform: device
    device_id: !input shelly_device
    domain: shelly
    type: single
    subtype: !input input_channel
    id: single
  - platform: device
    device_id: !input shelly_device
    domain: shelly
    type: double
    subtype: !input input_channel
    id: double
  - platform: device
    device_id: !input shelly_device
    domain: shelly
    type: triple
    subtype: !input input_channel
    id: triple
  - platform: device
    device_id: !input shelly_device
    domain: shelly
    type: long
    subtype: !input input_channel
    id: long
  - platform: device
    device_id: !input shelly_device
    domain: shelly
    type: single_long
    subtype: !input input_channel
    id: single_long
  - platform: device
    device_id: !input shelly_device
    domain: shelly
    type: long_single
    subtype: !input input_channel
    id: long_single

action:
  - choose:
      # --- Single Click → Toggle light ---
      - conditions:
          - condition: trigger
            id: single
        sequence:
          - service: light.toggle
            target: !input target_light

      # --- Double Click → Max brightness ---
      - conditions:
          - condition: trigger
            id: double
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_pct: 100

      # --- Triple Click → Turn off ---
      - conditions:
          - condition: trigger
            id: triple
        sequence:
          - service: light.turn_off
            target: !input target_light

      # --- Long / Single_Long / Long_Single → Continuous Dim ---
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['long', 'single_long', 'long_single'] }}"
        sequence:
          - service: input_boolean.toggle
            target:
              entity_id: "{{ dim_toggle }}"
          - variables:
              dim_up: "{{ is_state(dim_toggle, 'on') }}"
          - repeat:
              while:
                - condition: template
                  value_template: >
                    {% if hold_sensor != [] %}
                      {{ is_state(hold_sensor, 'on') }}
                    {% else %}
                      true
                    {% endif %}
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: "{{ 5 if dim_up else -5 }}"
                - delay: "00:00:0.2"
