blueprint:
  name: Shelly Virtual Dimmer Controller
  description: >
    Use a Shelly Dimmer 2 as a virtual dimmer controller for other lights.
    Supports single/double/long/single_long/long_single clicks.
  domain: automation
  author: HomeAssistant Helper (GPT-5)
  homeassistant:
    min_version: 2025.10.0

  input:
    shelly_click:
      name: Shelly Click Event
      description: Select the Shelly event entity (e.g., button or binary_sensor)
      selector:
        entity:
          domain: sensor
    target_light:
      name: Target Light(s)
      description: Light(s) to control
      selector:
        target:
          entity:
            domain: light
    dim_direction_helper:
      name: Dim Direction Toggle
      description: An input_boolean helper used to track dim direction (up/down)
      selector:
        entity:
          domain: input_boolean

mode: restart
max_exceeded: silent

variables:
  light_target: !input target_light
  dim_toggle: !input dim_direction_helper

trigger:
  - platform: state
    entity_id: !input shelly_click

action:
  - variables:
      click_type: "{{ trigger.to_state.state }}"

  - choose:
      # --- Single Click ---
      - conditions:
          - condition: template
            value_template: "{{ click_type == 'single' }}"
        sequence:
          - service: light.toggle
            target: !input target_light

      # --- Double Click ---
      - conditions:
          - condition: template
            value_template: "{{ click_type == 'double' }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_pct: 100

      # --- Long Press (Continuous Dim) ---
      - conditions:
          - condition: template
            value_template: "{{ click_type in ['long', 'single_long', 'long_single'] }}"
        sequence:
          - service: input_boolean.toggle
            target:
              entity_id: "{{ dim_toggle }}"
          - variables:
              dim_up: "{{ is_state(dim_toggle, 'on') }}"
          - repeat:
              while:
                - condition: template
                  value_template: "{{ is_state(trigger.entity_id, 'long') }}"
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: "{{ 5 if dim_up else -5 }}"
                - delay: "00:00:0.2"

      # --- Triple Click (Optional Action Example) ---
      - conditions:
          - condition: template
            value_template: "{{ click_type == 'triple' }}"
        sequence:
          - service: light.turn_off
            target: !input target_light

  # Stop dimming when button released
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ click_type not in ['long', 'single_long', 'long_single'] }}"
        sequence:
          - stop: "Stop continuous dimming"
