blueprint:
  name: Continuous Dimming Loop2
  description: >
    Reusable script for continuous dimming (hold to brighten or dim).
    Call from automations (e.g. Shelly, Zigbee buttons, etc.) on long-press.
  domain: script
  author: HomeAssistant Helper GPT-5

  input:
    light_entity:
      name: Target Light
      selector:
        entity:
          domain: light

    direction:
      name: Direction
      description: "1 = brighten, -1 = dim"
      default: 1
      selector:
        number:
          min: -1
          max: 1
          step: 2

    step:
      name: Brightness Step (%)
      default: 4
      selector:
        number:
          min: 1
          max: 20
          unit_of_measurement: "%"

    delay:
      name: Delay Between Steps (ms)
      default: 120
      selector:
        number:
          min: 50
          max: 1000
          unit_of_measurement: "ms"

    min_brightness:
      name: Minimum Brightness (%)
      default: 5
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"

    max_brightness:
      name: Maximum Brightness (%)
      default: 100
      selector:
        number:
          min: 50
          max: 100
          unit_of_measurement: "%"

mode: restart

sequence:
  - repeat:
      while: []
      sequence:
        - service: light.turn_on
          target:
            entity_id: !input light_entity
          data:
            brightness_pct: >-
              {{
                [
                  [
                    ((state_attr(!input light_entity, 'brightness') | int(0)) / 2.55) | int + (!input step * !input direction),
                    !input max_brightness
                  ] | min,
                  !input min_brightness
                ] | max
              }}
        - delay:
            milliseconds: !input delay
